env := "main"

deploy docker_image:
  ansible-galaxy install -r requirements.yml
  ansible-playbook \
    -i inventory/{{ env }}/hosts.ini \
    -e rustify_docker_image="{{ docker_image }}" \
    -t project \
    --diff \
    playbook.yml
