---
- name: Simple Rustify Deploy Ansible Playbook
  hosts: all
  vars:
    files_path: ../..
    backups_path: "{{ files_path }}/var/backup"
    backup_path: "{{ backups_path }}/{{ ansible_date_time.iso8601 }}"
    executable_path: target/x86_64-unknown-linux-gnu/release/rustify

  roles:
    - role: geerlingguy.docker
      docker_package_state: latest

  tasks:
    - name: Install System Packages
      block:
        - name: Apt Install Prerequisites
          ansible.builtin.apt:
            name: [python3, python3-pip]
            state: latest
            update_cache: true

        - name: Install Python Packages
          ansible.builtin.pip:
            name:
              - docker
              - docker-compose
            state: present

    - name: Backup Database
      vars:
        backup_files:
          - data.db
          - data.db-shm
          - data.db-wal

      block:
        - name: Create temp
          ansible.builtin.tempfile:
            state: directory
            suffix: rustify_backup
          register: rustify_backup_tmp

        - name: Copy Database Files
          register: backup_database_res
          retries: 5
          until: backup_database_res is not failed
          ansible.builtin.copy:
            src: "{{ deploy_path }}/var/{{ item }}"
            dest: "{{ rustify_backup_tmp.path }}/{{ item }}"
            remote_src: true
          loop: "{{ backup_files }}"

        - name: Backup Folder Create
          ansible.builtin.file:
            path: "{{ backup_path }}"
            state: directory
            mode: 0755
          delegate_to: localhost

        - name: Backup Database Files
          register: backup_database_res
          retries: 5
          until: backup_database_res is not failed
          ansible.builtin.fetch:
            src: "{{ rustify_backup_tmp.path }}/{{ item }}"
            dest: "{{ backup_path }}/"
            fail_on_missing: false
            flat: true
          loop: "{{ backup_files }}"

        - name: Delete temp folder
          ansible.builtin.file:
            path: "{{ rustify_backup_tmp.path }}"
            state: absent

    - name: Deploy
      block:
        - name: Create Directories
          ansible.builtin.file:
            path: "{{ item }}"
            state: directory
            mode: 0644
          loop:
            - "{{ deploy_path }}"
            - "{{ deploy_path }}/var"
            - "{{ deploy_path }}/{{ executable_path | dirname }}"

        - name: Copy Text Files
          ansible.builtin.copy:
            src: "{{ files_path }}/{{ item }}"
            dest: "{{ deploy_path }}/{{ item }}"
            mode: 0644
          loop:
            - docker-compose.yml
            - Dockerfile
            - .env.deploy
            - proxychains.conf

        - name: Copy Executables
          ansible.builtin.copy:
            src: "{{ files_path }}/{{ item }}"
            dest: "{{ deploy_path }}/{{ item }}"
            mode: 0755
          loop:
            - "{{ executable_path }}"

        - name: Docker Compose Up
          community.docker.docker_compose:
            project_src: "{{ deploy_path }}"
            build: true
            state: present
            recreate: always

    - name: Backup Cleanup
      block:
        - name: Find Backup Folders
          ansible.builtin.find:
            paths: "{{ backups_path }}"
            file_type: directory
          delegate_to: localhost
          register: backups

        - name: Backup Folder Names
          ansible.builtin.set_fact:
            backups_delete: "{{ backups.files | sort(attribute='path') | map(attribute='path') | list }}"

        - name: Delete Old Backup Folders
          ansible.builtin.file:
            path: "{{ item }}"
            state: absent
          delegate_to: localhost
          loop: "{{ backups_delete[0:-5] }}"
