use std::process::Command;

// generated by `sqlx migrate build-script`
fn main() {
    // trigger recompilation when a new migration is added
    println!("cargo:rerun-if-changed=migrations");

    Command::new("sea-orm-cli")
        .args(&[
            "generate",
            "entity",
            "-o",
            "src/entity",
            "--expanded-format",
            "--with-serde",
            "both",
        ])
        .status()
        .unwrap();
}
