//! SeaORM Entity. Generated by sea-orm-codegen 0.5.0

pub mod prelude;

mod spotify_auth;
mod track_status;
mod user;
mod user_whitelist;
mod user_word_whitelist;
mod word_definition;
mod word_stats;
