---
- name: Create Directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: "0644"
  loop:
    - "{{ rustify_deploy_path }}"
    - "{{ rustify_deploy_path }}/var"

- name: Login into Container registry
  docker_login:
    registry: "{{ rustify_docker_registry_url }}"
    username: "{{ rustify_docker_registry_username }}"
    password: "{{ rustify_docker_registry_password }}"
    reauthorize: yes
  when: rustify_docker_registry

- name: Docker Compose
  ansible.builtin.template:
    src: docker-compose.yml.j2
    dest: "{{ rustify_deploy_path }}/docker-compose.yml"
    mode: "0644"

- name: Docker Compose Up
  community.docker.docker_compose:
    project_src: "{{ rustify_deploy_path }}"
    build: true
    state: present
    recreate: always

- name: Configure Backups
  block:
    - name: Copy Backup Text Files
      ansible.builtin.template:
        src: "{{ item.key }}"
        dest: "{{ rustify_deploy_path }}/{{ item.value }}"
        mode: 0644
      with_dict:
        "docker-compose.backup.yml.j2": docker-compose.backup.yml

    - name: "Cron: Upload backup with restic"
      ansible.builtin.cron:
        name: "run restic backup"
        day: "*/4"
        hour: "0"
        minute: "30"
        job: "/usr/local/bin/docker-compose -f {{ rustify_deploy_path }}/docker-compose.backup.yml -p rustify-backup run --rm backup"

    - name: "Cron: Cleanup old backups"
      ansible.builtin.cron:
        name: "run restic forget"
        weekday: "6"
        hour: "0"
        minute: "0"
        job: "/usr/local/bin/docker-compose -f {{ rustify_deploy_path }}/docker-compose.backup.yml -p rustify-backup run --rm forget"
